### ISSUE TITLE
Not working with zig 0.15

### ISSUE THREAD

**Issue by StephanMoeller** [lawrence-laz/neotest-zig#41]
**Describe the bug**
When running zig tests in my microzig project, using neotest with neotest-zig, using zig version 0.14.1 work just fine. When using zig version 0.15 I get an error:

## **Steps To Reproduce**
Install zig 0.15
Create a new folder named "test" and navigate into this
run zig init
run zig build test => verifies that this does not give any errors
now open the folder in neovim, using this neotree config:

return {
  {
    "nvim-neotest/neotest",
    dependencies = {
      "lawrence-laz/neotest-zig", -- Installation
      "nvim-lua/plenary.nvim",
      "nvim-treesitter/nvim-treesitter",
      "antoinemadec/FixCursorHold.nvim",
    },
    config = function()
      local neotest = require("neotest")
      neotest.setup({
        adapters = {
          -- Registration
          require("neotest-zig")({
            dap = {
              adapter = "lldb",
            },
          }),
        }
      })
      local opts = { noremap = true, silent = true }
      -- Run nearest test
      --vim.keymap.set("n", "<leader>tt", function() neotest.run.run() neotest.summary.open() end, opts)
    end
  },
  {
    { "nvim-neotest/nvim-nio" }
  }
}

Run neotest.

## **Current behavior**
I get this error:

test
└─ run test
   └─ compile test Debug native 1 errors
/home/.../.local/share/nvim/lazy/neotest-zig/zig/neotest_runner.zig:152:49: error: struct 'array_list.Aligned(neotest_runner.TestResult,null)' has no member named 'init'
    var test_results = std.ArrayList(TestResult).init(gpa.allocator());
                       ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~


## **Expected behavior**
I expected the tests to run successfully

## **Environment**
 - OS: Cacheos
 - Zig version: 0.15
 - Nvim version: 0.11.4
 - Neotest version: 5.9.0
 - Neotest Zig version: 1.4.0

**Comment by StephanMoeller** [comment]
I tried to upgrade to latest neotest  (5.11.1) and neotest-zig to 1.4.0 but this didnt solve the issues.

**Comment by StephanMoeller** [comment]
A solution might be available here: https://ziggit.dev/t/error-struct-array-list-aligned-u8-null-has-no-member-named-init/11757

**Comment by lawrence-laz** [comment]
Yes, the plugin needs to be updated to address zig v0.15 breaking changes. I cant make any promises about when I will get this done though. Maybe someone will contribute a PR in the meantime.

**Comment by arso** [comment]
Hi, I was recently playing with nvim 0.12 + zig 0.15 and finally managed to get  `neotest-zig` running. Please see [this PR](https://github.com/lawrence-laz/neotest-zig/pull/43).  
In theory it should work for earlier versions too - zig compiler skips  the compilation of inactive `if` branches. However, you might want to test in your own environment first.
